name: Setup Vulkan SDK

inputs:
  os:
    required: true
  vk-sdk:
    required: false
    default: '1.4.357.0'

runs:
  using: composite
  steps:
    - name: Cache Vulkan SDK
      id: cache-vulkan
      uses: actions/cache@v5
      with:
        path: ${{ github.workspace }}/VulkanSDK/${{ inputs.vk-sdk }}/
        key: vulkan-${{ runner.os }}-${{ inputs.vk-sdk }}-v0

    - name: Install VulkanSDK
      if: steps.cache-vulkan.outputs.cache-hit != 'true'
      shell: pwsh
      run: |
        if ("${{ inputs.os }}" -eq "Windows") {
          Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/${{ inputs.vk-sdk }}/windows/vulkansdk-windows-X64-${{ inputs.vk-sdk }}.exe" -OutFile VulkanSDK.exe
          ./VulkanSDK.exe --accept-licenses --default-answer --confirm-command install --root "${{ github.workspace }}/VulkanSDK/${{ inputs.vk-sdk }}/x86_64" 1>$null
          }
        if ("${{ inputs.os }}" -eq "Linux") {
          Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/${{ inputs.vk-sdk }}/linux/vulkansdk-linux-x86_64-${{ inputs.vk-sdk }}.tar.xz" -OutFile VulkanSDK.tar.xz
          mkdir -p VulkanSDK
          tar -xJf VulkanSDK.tar.xz -C ./VulkanSDK
          }

    - name: Setup VulkanSDK
      shell: pwsh
      run: |
        $env:VULKAN_SDK      = "${{ github.workspace }}/VulkanSDK/${{ inputs.vk-sdk }}/x86_64"
        $env:VK_LAYER_PATH   = "$env:VULKAN_SDK/etc/vulkan/explicit_layers.d"
        $env:LD_LIBRARY_PATH = "$env:VULKAN_SDK/lib"
        $env:LIBRARY_PATH    = "$env:VULKAN_SDK/lib/VulkanLoader/lib"

        echo "VULKAN_SDK=$env:VULKAN_SDK"           >> $env:GITHUB_ENV
        echo "VK_LAYER_PATH=$env:VK_LAYER_PATH"     >> $env:GITHUB_ENV
        echo "LD_LIBRARY_PATH=$env:LD_LIBRARY_PATH" >> $env:GITHUB_ENV
        echo "$env:VULKAN_SDK/Bin"                  >> $env:GITHUB_PATH
        echo "LIBRARY_PATH=$env:LIBRARY_PATH"       >> $env:GITHUB_ENV