#version 450

#include "lighting/surfels/surf_common.glsl"
#include "scene.glsl"
#include "common.glsl"

layout(local_size_x = 64) in;

layout(std140, push_constant) uniform Push {
  vec3 originLwc;
  uint maxSurfels;
  };
layout(binding = 0, std140) uniform UboScene {
  SceneDesc scene;
  };

layout(binding = 1) uniform sampler2D  gbufDiffuse;
layout(binding = 2) uniform usampler2D gbufNormal;
layout(binding = 3) uniform sampler2D  depth;
layout(binding = 4, std430) buffer SB0 { uvec4 count; Surfel surfels[]; };
//
layout(binding = 6) uniform sampler2D pdfTree;

vec3 worldPos(float z, ivec2 fragCoord, ivec2 screenSize) {
  const mat4 inv = scene.viewProjectLwcInv;
  const vec2 uv  = vec2(fragCoord+0.5)*scene.screenResInv;
  const vec4 pos = inv*vec4(uv * 2.0 - 1.0, z, 1);
  return pos.xyz/pos.w + originLwc;
  }

uint pdfFetch(in usampler2D pdfTree, ivec2 at, int mip) {
  const ivec2 sz = textureSize(pdfTree, mip);
  if(at.x>=sz.x || at.y>=sz.y)
    return 0;
  return texelFetch(pdfTree, at, mip).x;
  }

void sampleTree(ivec2 coord0, ivec2 coord1, int mip, inout float index, inout ivec2 p) {
  for(int i=coord0.x; i<coord1.x; ++i) {
    for(int r=coord0.y; r<coord1.y; ++r) {
      float v = texelFetch(pdfTree, ivec2(i,r), mip).x;
      if(index < v) {
        p = ivec2(i,r);
        return;
        }
      index = index-v;
      }
    }
  }

ivec2 find(float indexF, float maxV) {
  const int mipCount = textureQueryLevels(pdfTree);

  float index = indexF*maxV;
  ivec2 p     = ivec2(0);
  for(int i=mipCount-1; i>0;) {
    --i;

    ivec2 srcSize = textureSize(pdfTree, i+0);
    ivec2 dstSize = textureSize(pdfTree, i+1);

    ivec2 coord0  = p*2;
    ivec2 coord1  = coord0+2;
    if(p.x+1==dstSize.x)
      coord1.x = srcSize.x;
    if(p.y+1==dstSize.y)
      coord1.y = srcSize.y;
    p *= 2;
    sampleTree(coord0, coord1, i, index, p);
    }

  return p;
  }

void main() {
  const uint  index    = gl_GlobalInvocationID.x;
  const int   mipCount = textureQueryLevels(pdfTree);
  const float maxV     = texelFetch(pdfTree, ivec2(0), mipCount-1).x;
  const uint  maxN     = count.y;
  if(index>=maxN || index>=maxSurfels)
    return;

  const ivec2 at = find(index/float(maxSurfels), maxV);

  if(at.x<0)
    return; //error

  const uint id = atomicAdd(count.x, 1);
  if(id>=surfels.length())
    return;

  const ivec2 screenSize = ivec2(textureSize(depth,0));
  const float z          = texelFetch(depth, at, 0).x;
  if(z==1.0)
    return;

  Surfel sx;
  sx.pos  = worldPos(z, at, screenSize);
  sx.norm = texelFetch(gbufNormal, at, 0).r;
  surfels[id] = sx;
  }