#version 450

layout(local_size_x = 8, local_size_y = 8) in;

layout(binding = 0, r32f) uniform readonly  image2D srcMip;
layout(binding = 1, r32f) uniform writeonly image2D dstMip;

void main() {
  ivec2 dstCoord = ivec2(gl_GlobalInvocationID.xy);
  ivec2 dstSize  = imageSize(dstMip);
  ivec2 srcSize  = imageSize(srcMip);

  if(dstCoord.x >= dstSize.x || dstCoord.y >= dstSize.y)
    return;

  ivec2 coord0 = dstCoord * 2;
  ivec2 coord1 = coord0+2;

  // bottom-right corner might have 3x3 footprint in npot image
  if(dstCoord.x+1==dstSize.x)
    coord1.x = srcSize.x;
  if(dstCoord.y+1==dstSize.y)
    coord1.y = srcSize.y;

  float ret = 0;
  for(int i=coord0.x; i<coord1.x; ++i) {
    for(int r=coord0.y; r<coord1.y; ++r) {
      float texel = imageLoad(srcMip, ivec2(i,r)).x;
      ret += texel;
      }
    }

  imageStore(dstMip, dstCoord, vec4(ret));
  }