#version 450

#include "lighting/surfels/surf_common.glsl"
#include "scene.glsl"
#include "common.glsl"

layout(local_size_x = 64) in;

layout(std140, push_constant) uniform Push {
  vec3 originLwc;
  };
layout(binding = 0, std140) uniform UboScene {
  SceneDesc scene;
  };
layout(binding = 4, std430) buffer SB0 { uvec4 count; Surfel surfels[];  } surf;
layout(binding = 8, std430) buffer SB2 { uvec4 count; SurfelAlloc req[]; } alloc;
layout(binding = 9, std430) buffer SB3 { uint deduplication[]; };

void main() {
  const uint allocId = gl_GlobalInvocationID.x;
  if(allocId>=alloc.count.x || allocId>=alloc.req.length())
    return;

  const SurfelAlloc p = alloc.req[allocId];

  if(p.reuseId!=0xFFFFFFFF) {
    const uint bit  = (1u << (p.reuseId % 32));
    const uint prev = atomicOr(deduplication[p.reuseId/32], bit);
    if((bit & prev)!=0)
      return;
    }

  const uint surfelId = atomicAdd(surf.count.x,1);

  Surfel sx;
  sx.pos        = p.pos.xyz;
  sx.norm       = encodeNormal(p.norm);
  sx.radius     = p.pos.w;
  sx.radiusPix  = DefaultCoverage; //TODO: calculate dynamically
  sx.irradiance = surfDebugColor(p.pos.xyz, surfelId);

  surf.surfels[surfelId] = sx;
  }
