#version 460

#include "lighting/surfels/surf_common.glsl"

layout(local_size_x = 128) in;

const uint NumThreads = gl_WorkGroupSize.x*gl_WorkGroupSize.y*gl_WorkGroupSize.z;

layout(binding = 5, std430)            buffer SB0 { uvec4 count; Candidate candidate[]; } alloc;
layout(binding = 6, std430) readonly   buffer SB2 { uint  surfelList[]; };
layout(binding = 7, r32ui) uniform uimage2D surfCnts;
layout(binding = 8, r32ui) uniform uimage2D surfBins;
layout(binding = 9, r32f)  uniform image2D  surfPdf;

shared float reduction[NumThreads];

void reduceWeights(float w) {
  uint laneID = gl_LocalInvocationIndex;

  reduction[laneID] = w;

  for(uint stride = NumThreads/2; stride > 0; stride >>= 1) {
    barrier();
    if(laneID < stride) {
      reduction[laneID] += reduction[laneID + stride];
      }
    }
  }

void main() {
  const ivec2 tileId = ivec2(gl_WorkGroupID.xy);
  const uint  cnt    = imageLoad(surfCnts, tileId).x;
  const uint  ptr    = imageLoad(surfBins, tileId).x;

  float wSum = 0;
  for(uint i=gl_LocalInvocationIndex; i<cnt; i+=NumThreads) {
    const uint sId = surfelList[ptr+i];
    wSum += alloc.candidate[sId].weight;
    }
  reduceWeights(wSum);

  if(gl_LocalInvocationIndex==0) {
    imageStore(surfPdf, tileId, vec4(reduction[0]));
    }
  }