#version 460

#define LIGHTING 1
#define RAY_QUERY
#define RAY_QUERY_AT

// #define RTAO

#include "lighting/rt/rt_common.glsl"
#include "lighting/pt/pathtrace_common.glsl"
#include "lighting/surfels/surf_common.glsl"
#include "lighting/lightstree/lights_common.glsl"
#include "lighting/tonemapping.glsl"

#include "scene.glsl"
#include "common.glsl"
#include "random.glsl"

layout(local_size_x = 64) in;

const uint NumThreads = gl_WorkGroupSize.x*gl_WorkGroupSize.y*gl_WorkGroupSize.z;
const int  numBounces = 5;
// const int  numBounces = 1;

layout(std140, push_constant) uniform Push {
  uint pass;
  };
layout(binding = 0, std140) uniform UboScene {
  SceneDesc scene;
  };
layout(binding = 1, std430) buffer SB0 { SurfHeader header; Surfel surfels[]; };
layout(binding = 2) uniform sampler2D skyLUT;

layout(binding = 13, std430) readonly buffer BVH {
  BVHNode node[];
  } bvhData;

mat3 toTangent(vec3 norm) {
  mat3 tangent;
  // Compute a tangent frame and rotate the half vector to world space
  vec3 up   = abs(norm.z) < 0.999f ? vec3(0.0f, 0.0f, 1.0f) : vec3(1.0f, 0.0f, 0.0f);
  tangent[0] = normalize(cross(up, norm));
  tangent[1] = cross(norm, tangent[0]);
  tangent[2] = norm;
  return tangent;
  }

float pixelToWorld(float pixelRadius, float z) {
  return pixelToWorld(scene, pixelRadius, z);
  }

float sampleDirectLight(vec3 norm, vec3 rayOrigin, vec3 rayDirection, bool shadowed, float softAngle, inout Random rngState) {
#if defined(SOFT_SHADOW)
  vec3  shRay  = randomizeRay(rayDirection, 0.5*M_PI/180.0, rngState);
#else
  vec3  shRay  = rayDirection;
#endif

  float lamb   = max(dot(norm, rayDirection), 0);
  if(!shadowed || lamb==0)
    return lamb;

  float shadow = rayQueryProceedShadow(rayOrigin, shRay, rngState);
  // float shadow = shadowFactor(rayOrigin);
  return (lamb * shadow);
  }

vec3 traverseLightTree(const vec3 wpos, const vec3 norm) {
  uint stack[32];
  uint ptr = 0;

  vec3 ret  = vec3(0);
  uint node = 0 | BVH_BoxNode;
  while(node!=0) {
    const uint    type = bvhGetNodeType(node);
    const BVHNode n    = bvhData.node[node & 0x0FFFFFFF];

    if(ptr==stack.length()) {
      // stack overflow
      return vec3(1,0,0);
      }

    if(type==BVH_LightNode) {
      // light
      const vec3  src       = n.lmin;
      const vec3  distance  = wpos - src;
      const float tMax      = length(distance);
      const vec3  ldir      = distance/tMax;
      const float intensity = lightIntensity(norm, tMax, ldir, uintBitsToFloat(n.ptrL));
      ret += intensity * n.lmax.rgb;
      }
    else {
      const bool left  = bvhIntersectBox(wpos, n.lmin, n.lmax);
      const bool right = bvhIntersectBox(wpos, n.rmin, n.rmax);
      if(left && right) {
        node         = n.ptrL;
        stack[ptr++] = n.ptrR;
        continue;
        }
      else if(left) {
        node = n.ptrL;
        continue;
        }
      else if(right) {
        node = n.ptrR;
        continue;
        }
      }
    if(ptr == 0)
      break;
    node = stack[--ptr];
    }

  return ret;
  }

vec4 pathtrace(vec3 rayOrigin, vec3 rayDirection, inout Random rngState) {
  vec3  thruput    = vec3(1);
  vec3  color      = vec3(0);
  bool  underWater = (scene.underWater!=0);
  float depth      = 0;

  for(int bounce=0;; ++bounce) {
    if(dot(thruput*scene.GSunIntensity*scene.exposure, vec3(0.2126, 0.7152, 0.0722)) < 0.01)
      break;

    if(bounce>=numBounces) {
      // return 0.5*vec4(1,0,1,depth)*scene.GSunIntensity;
      // rescale to 100% thruput
      /*
      vec3 scale = 1.0-thruput;
      if(scale.r>0.01 && scale.g>0.01 && scale.b>0.01)
        return vec4(color/scale, depth);
      */
      return vec4(color, depth);
      }

    HitResolve hit = rayQueryProceedPrimary(rayOrigin, rayDirection, -1, rngState);
    if(bounce==0)
      depth = abs(hit.rayT);

    if(hit.rayT<0) {
      hit.rayT = abs(hit.rayT); // backfaces are fine for PT
      hit.norm = -hit.norm;
      }

    if(hit.rayT==TMax) {
      vec3 sky = textureSkyLUT(skyLUT, vec3(0,RPlanet+max(rayOrigin.y*0.01,0),0), rayDirection, scene.sunDir) * scene.GSunIntensity;
      color += thruput*sky;
      color += thruput*(vec3(0.3, 0.26, 1)*0.15); //HACK for the night sky
      break;
      }

#if defined(RTAO)
    return vec4(color, depth);
#endif

    rayOrigin    = (rayOrigin + rayDirection * hit.rayT);
    rayDirection = randCosWeightedHemisphereDirection(hit.norm, rngState);
    thruput     *= min(textureAlbedo(hit.diff.rgb), 0.95);
    //thruput    *= vec3(0.85); //snow
    //thruput    *= vec3(0.04); // asphalt
    //if(bounce>0)
    //  thruput *= groundAlbedo;
    //if(bounce>0)
    //  thruput    *= textureAlbedo(hit.diff.rgb);

    vec3  direct = vec3(0);
    direct += sampleDirectLight(hit.norm, rayOrigin, scene.sunDir, true, 0.54*M_PI/180.0, rngState);
    direct += traverseLightTree(rayOrigin, hit.norm) * (max(1.0, scene.exposure) / scene.exposure);
    color  += thruput*direct*Fd_Lambert;
    }

  return vec4(color, depth);
  }

shared vec4 reduction[NumThreads];

void reduceIrr() {
  uint laneID = gl_LocalInvocationIndex;

  for(uint stride = NumThreads/2; stride > 0; stride >>= 1) {
    if(laneID < stride) {
      reduction[laneID] += reduction[laneID + stride];
      }
    barrier();
    }
  }

void main() {
  const float eps      = 0.0001;
  const uint  numPaths = NumThreads;
  const uint  surfelId = pass==0 ? gl_WorkGroupID.x : (header.count-gl_WorkGroupID.z-1);
  // if(surfelId>=header.count)
  //   return;

  const Surfel p   = surfels[surfelId];
  const mat3   tbn = toTangent(decodeNormal(p.norm));

  Random rngState = Random(pcgHash(gl_LocalInvocationIndex));

  const uint i   = gl_LocalInvocationIndex;
  const vec3 ray = tbn * sampleHemisphereCos(i,numPaths,0);
  // const vec3 ray = randCosWeightedHemisphereDirection(decodeNormal(p.norm), rngState);
  const vec4 pt  = pathtrace(p.pos, ray, rngState);

  float hitInv = 1.0/clamp(pt.a*0.4, 10.0, p.radius);
  reduction[i] = vec4(pt.rgb*scene.exposure, hitInv);
  barrier();

  reduceIrr();

  if(gl_LocalInvocationIndex==0) {
    const vec4   pos4 = scene.viewProject * vec4(p.pos, 1.0);
    const float  rMin = pixelToWorld(MinCoverage, pos4.z/pos4.w);
    const float  rMax = min(pixelToWorld(DefaultCoverage, pos4.z/pos4.w), 65000);

    const float hitMean = float(numPaths)/max(reduction[0].w, eps); //harmonic mean
    surfels[surfelId].radius     = rMax;
    surfels[surfelId].radiusMean = min(max(hitMean, rMin), rMax * rEffScale);

    surfels[surfelId].irradiance = (reduction[0].rgb/float(numPaths));
    }
  }