#version 450

#include "lighting/surfels/surf_common.glsl"
#include "scene.glsl"
#include "common.glsl"

layout(local_size_x = 16, local_size_y = 16) in;

const uint NumThreads = gl_WorkGroupSize.x*gl_WorkGroupSize.y*gl_WorkGroupSize.z;

const ivec2 TileSize   = ivec2(128);
const float NormalBias = 0.0030;
const uint  Salt       = 0x9D;
const float Edge       = 0.15;

layout(std140, push_constant) uniform Push {
  vec3 originLwc;
  };
layout(binding = 0, std140) uniform UboScene {
  SceneDesc scene;
  };
layout(binding = 1) uniform sampler2D  gbufDiffuse;
layout(binding = 2) uniform usampler2D gbufNormal;
layout(binding = 3) uniform sampler2D  depth;
layout(binding = 4, std430)          buffer SB0 { uvec4 count; Surfel surfels[]; } glob;
layout(binding = 5, std430) readonly buffer SB1 { uint surfelList[]; };
layout(binding = 6, r32ui) uniform uimage2D surfCnts;
layout(binding = 7, r32ui) uniform uimage2D surfBins;
layout(binding = 8, std430)          buffer SB2 { uvec4 count; SurfelAlloc req[]; } alloc;
//
layout(binding = 11, rgba8) uniform image2D dbgImage;

shared SurfelAlloc prevQueue [256];
shared SurfelAlloc pointQueue[128];
shared int         pointQueueSize;
shared int         prevQueueSize;

shared uint fragVote, reuseVote;

vec3 rayOrigin(ivec2 frag, float depth, vec3 normal) {
  const vec2 fragCoord = ((frag.xy+0.5)*scene.screenResInv)*2.0 - vec2(1.0);
  const vec4 scr       = vec4(fragCoord.x, fragCoord.y, depth, 1.0);
  const vec4 wpos      = scene.viewProjectLwcInv * scr;
  return (wpos.xyz + normal*NormalBias)/wpos.w;
  }

vec3 worldPos(float z, vec3 normal, ivec2 fragCoord, ivec2 screenSize) {
  const mat4 inv = scene.viewProjectLwcInv;
  const vec2 uv  = vec2(fragCoord+0.5)*scene.screenResInv;
  const vec4 pos = inv*vec4(uv * 2.0 - 1.0, z, 1);
  return (pos.xyz + normal*NormalBias)/pos.w + originLwc;
  }

float pixelToWorld(float pixelRadius, float z) {
  z = linearDepth(z, scene.clipInfo);

  float clipRadiusX = (2.0 * pixelRadius) * scene.screenResInv.x;
  float clipRadiusY = (2.0 * pixelRadius) * scene.screenResInv.y;

  float worldRadiusX = (clipRadiusX * z) / scene.project[0][0];
  float worldRadiusY = (clipRadiusY * z) / scene.project[1][1];
  return min(worldRadiusX, worldRadiusY);
  }

float calculteWeight(const SurfelAlloc s, const vec3 wpos, const vec3 norm) {
  return calculteWeight(s.pos.xyz, s.norm, s.pos.w, wpos, norm);
  }

float seedNoise(vec3 wpos, float z, const ivec2 screenSize) {
  uvec3 p = uvec3(wpos/32);
  return (pcgHash(p.x + pcgHash(p.y + pcgHash(p.z)))/4294967296.0)*0.1;
  }

void mainTile(const ivec2 fragCoord, const ivec2 screenSize) {
  const bool  valid = all(lessThan(fragCoord, screenSize));
  if(!valid)
    return;

  const float z     = texelFetch(depth,fragCoord,0).x;
  const bool  sky   = (z >= SKY_DEPTH);
  if(sky)
    return;

  const vec3  norm = normalFetch(gbufNormal, fragCoord);
  const vec3  wpos = worldPos(z, norm, fragCoord, screenSize);

  uvec3 p    = uvec3(wpos/10);
  float wMax = seedNoise(wpos, z, screenSize)*0.1;
  for(int i=pointQueueSize; i>0;) {
    --i;
    const SurfelAlloc s = pointQueue[i];
    const float       w = calculteWeight(s,wpos,norm);
    // w = max(w,0);
    wMax = max(wMax,w);
    if(wMax > Edge)
      break;
    }

  imageStore(dbgImage, fragCoord, vec4(wMax-Edge));

  if(wMax > Edge)
    return;

  uint  w = floatBitsToUint(wMax/Edge) & 0xFFFF0000;
  uint  b = uint(w) | uint(gl_LocalInvocationIndex) ^ Salt;
  atomicMin(fragVote, b);
  }

void reuseSurfel(ivec2 fragCoord, const ivec2 screenSize) {
  const uint laneID = gl_LocalInvocationIndex;

  const uint vote = fragVote;
  //reuseVote = 0x0000FFFF;
  barrier();

  if((vote & 0xFFFF0000)==0xFFFF0000)
    return;

  const uint id = (vote & 0xFFFF) ^ Salt;
  fragCoord.x += int(id % gl_WorkGroupSize.x);
  fragCoord.y += int(id / gl_WorkGroupSize.x);

  const float z    = texelFetch(depth, fragCoord, 0).x;
  const vec3  norm = normalFetch(gbufNormal, fragCoord);
  const vec3  wpos = worldPos(z, norm, fragCoord, screenSize);

  if(laneID<prevQueueSize) {
    const float wsurf = calculteWeight(prevQueue[laneID],wpos,norm);
    if(wsurf > Edge) {
      uint  w = floatBitsToUint(wsurf) & 0xFFFF0000;
      uint  b = uint(w) | uint(laneID);
      atomicMax(reuseVote, b);
      }
    }
  barrier();

  if(laneID!=0)
    return;

  const uint reuseId = reuseVote & 0x0000FFFF;
  if(reuseId==0x0000FFFF || pointQueueSize>=pointQueue.length())
    return;

  fragVote  = 0xFFFFFFFF;
  reuseVote = 0x0000FFFF;

  pointQueue[pointQueueSize] = prevQueue[reuseId];
  pointQueueSize++;

  prevQueue[reuseId] = prevQueue[prevQueueSize-1];
  prevQueueSize--;
  }

void surfAlloc(ivec2 fragCoord, const ivec2 screenSize) {
  if(gl_LocalInvocationIndex!=0)
    return;

  if(pointQueueSize>=pointQueue.length()) {
    return;
    }

  const uint vote = fragVote;
  fragVote = 0xFFFFFFFF;

  if((vote & 0xFFFF0000)==0xFFFF0000)
    return;

  const uint id = (vote & 0xFFFF) ^ Salt;
  fragCoord.x += int(id % gl_WorkGroupSize.x);
  fragCoord.y += int(id / gl_WorkGroupSize.x);

  const float z    = texelFetch(depth, fragCoord, 0).x;
  const vec3  norm = normalFetch(gbufNormal, fragCoord);
  const vec3  wpos = worldPos(z, norm, fragCoord, screenSize);
  const float sz   = max(pixelToWorld(DefaultCoverage, z), 0);

  SurfelAlloc s;
  s.pos     = vec4(wpos, sz);
  s.norm    = norm;
  s.reuseId = 0xFFFFFFFF;
  pointQueue[pointQueueSize] = s;
  pointQueueSize++;
  }

void storeSurfels() {
  const uint laneID = gl_LocalInvocationIndex;

  if(laneID==0) {
    pointQueueSize = min(pointQueueSize, pointQueue.length());
    fragVote = atomicAdd(alloc.count.x, pointQueueSize);
    }
  barrier();

  if(laneID<pointQueueSize) {
    const uint ptr = fragVote + laneID;
    if(ptr<alloc.req.length())
      alloc.req[ptr] = pointQueue[laneID];
    }
  }

void loadTile(ivec2 tileId) {
  const uint laneID = gl_LocalInvocationIndex;

  const uint cnt = imageLoad(surfCnts, tileId).x;
  const uint ptr = imageLoad(surfBins, tileId).x;

  ivec2 bboxMin = ivec2(gl_WorkGroupID.xy*TileSize);
  ivec2 bboxMax = bboxMin + ivec2(TileSize);

  if(laneID==0)
    prevQueueSize = int(min(cnt, prevQueue.length()));
  barrier();

  for(uint i=laneID; i<prevQueueSize; i+=NumThreads) {
    const uint   sId = surfelList[ptr+i];
    const Surfel sx  = glob.surfels[sId];

    SurfelAlloc s;
    s.pos     = vec4(sx.pos, sx.radius);
    s.norm    = decodeNormal(sx.norm);
    s.reuseId = sId;
    prevQueue[i] = s;
    }
  }

void main() {
  // if(gl_WorkGroupID.xy!=uvec2(8,5) && gl_WorkGroupID.xy!=uvec2(8,6))
  //   return;
  if(!(7 < gl_WorkGroupID.x && gl_WorkGroupID.x<=9 &&
       3 < gl_WorkGroupID.y && gl_WorkGroupID.y<=6))
    ;//return;

  pointQueueSize = 0;
  prevQueueSize  = 0;
  fragVote       = 0xFFFFFFFF;
  reuseVote      = 0x0000FFFF;
  barrier();

  const ivec2 tileId = ivec2(gl_WorkGroupID.xy*TileSize)/int(TileSize);
  loadTile(tileId);
  barrier();

  const ivec2 screenSize = ivec2(textureSize(depth,0));

  const ivec2 coord0 = ivec2(gl_WorkGroupID.xy) * TileSize;
  const ivec2 coord1 = ivec2(gl_WorkGroupID.xy) * TileSize + TileSize;

#if 1
  for(int y=coord0.y; y<coord1.y; y+=int(gl_WorkGroupSize.y))
    for(int x=coord0.x; x<coord1.x; x+=int(gl_WorkGroupSize.x)){
      mainTile(ivec2(x,y) + ivec2(gl_LocalInvocationID.xy), screenSize);
      barrier();

      reuseSurfel(ivec2(x,y), screenSize);
      barrier();

      surfAlloc(ivec2(x,y), screenSize);
      barrier();
      }
#endif

  storeSurfels();
  }
