#version 460

#define LIGHTING 1
#define RAY_QUERY
#define RAY_QUERY_AT

#include "lighting/rt/rt_common.glsl"
#include "lighting/pt/pathtrace_common.glsl"
#include "lighting/surfels/surf_common.glsl"
#include "lighting/tonemapping.glsl"

#include "scene.glsl"
#include "common.glsl"
#include "random.glsl"

layout(local_size_x = 8, local_size_y = 8) in;

const uint NumThreads = gl_WorkGroupSize.x*gl_WorkGroupSize.y*gl_WorkGroupSize.z;

layout(std140, push_constant) uniform Push {
  uint pass;
  };
layout(binding = 0, std140) uniform UboScene {
  SceneDesc scene;
  };
layout(binding = 1, std430) buffer SB0 { SurfHeader header; Surfel surfels[]; };
layout(binding = 2)         uniform sampler2D skyLUT;
layout(binding = 3)         uniform texture2D gbufDiff;
layout(binding = 4)         uniform texture2D gbufNorm;
layout(binding = 5)         uniform texture2D gbufHit;
layout(binding = 12)        uniform sampler2D textureSm1;

struct GBuf {
  vec3  diff;
  vec3  norm;
  float rayT;
  float rayW;
  };

shared vec4 reduction[NumThreads];

float shadowResolve(in vec4 sh, float z) {
  z  = clamp(z,0,0.99);
  sh = step(sh,vec4(z));
  return 0.25*(sh.x+sh.y+sh.z+sh.w);
  }

vec4 shadowSample(in sampler2D shadowMap, vec2 shPos) {
  shPos.xy = shPos.xy*vec2(0.5,0.5)+vec2(0.5);
  return textureGather(shadowMap,shPos);
  }

float calcShadow(vec3 shPos1) {
  vec4  lay1 = shadowSample(textureSm1,shPos1.xy);
  float v1   = shadowResolve(lay1,shPos1.z);
  return v1;
  }

mat3 toTangent(vec3 norm) {
  mat3 tangent;
  // Compute a tangent frame and rotate the half vector to world space
  vec3 up   = abs(norm.z) < 0.999f ? vec3(0.0f, 0.0f, 1.0f) : vec3(1.0f, 0.0f, 0.0f);
  tangent[0] = normalize(cross(up, norm));
  tangent[1] = cross(norm, tangent[0]);
  tangent[2] = norm;
  return tangent;
  }

float pixelToWorld(float pixelRadius, float z) {
  return pixelToWorld(scene, pixelRadius, z);
  }

float sampleDirectLight(vec3 norm, vec3 rayOrigin, vec3 rayDirection) {
  float lamb   = max(dot(norm, rayDirection), 0);
  if(lamb==0)
    return lamb;

  vec4 shCoord = scene.viewShadow[1]*vec4(rayOrigin,1);
  if(abs(shCoord.x)>=shCoord.w && abs(shCoord.y)>=shCoord.w) {
#if 1
    return 1;
#else
    Random rngState = Random(0);
    float shadow = rayQueryProceedShadow(rayOrigin, rayDirection, rngState);
    return (lamb * shadow);
#endif
    }
  float shadow = calcShadow(shCoord.xyz/shCoord.w);
  return (lamb * shadow);
  }

vec3 evalLight(vec3 rayOrigin, vec3 rayDirection, GBuf hit) {
  vec3  thruput = vec3(1.0);
  vec3  color   = vec3(0);

  if(hit.rayW > 0) {
    thruput *= waterTransmittance(hit.rayW);
    }

  if(hit.rayT==TMax) {
    vec3 sky = textureSkyLUT(skyLUT, vec3(0,RPlanet+max(rayOrigin.y*0.01,0),0), rayDirection, scene.sunDir) * scene.GSunIntensity;
    color += sky;
    color += (vec3(0.3, 0.26, 1)*0.15); //HACK for the night sky
    return thruput*color;
    }

  thruput  *= min(textureAlbedo(hit.diff.rgb), 0.95);
  rayOrigin = (rayOrigin + rayDirection * hit.rayT);

  vec3  direct = vec3(0);
  direct += sampleDirectLight(hit.norm, rayOrigin, scene.sunDir) * scene.sunColor;
  color  += thruput*direct*Fd_Lambert;

  return color;
  }

GBuf loadGBuf(uint ptr) {
  uint x = ((ptr >>  0) & 0xFFF);
  uint y = ((ptr >> 12) & 0xFFF);

  ivec2 at = ivec2(x,y)*8 + ivec2(gl_LocalInvocationID.xy);
  vec4  d  = texelFetch(gbufDiff, at, 0);
  vec4  n  = texelFetch(gbufNorm, at, 0);

  GBuf hit;
  hit.diff = d.rgb;
  hit.norm = n.xyz*2.0-1.0;
  hit.rayT = texelFetch(gbufHit,  at, 0).x * TMax;
  hit.rayW = n.w * hit.rayT;

  return hit;
  }

void reduceIrr() {
  uint laneID = gl_LocalInvocationIndex;

  for(uint stride = NumThreads/2; stride > 0; stride >>= 1) {
    if(laneID < stride) {
      reduction[laneID] += reduction[laneID + stride];
      }
    barrier();
    }
  }

void main() {
  const float eps      = 0.0001;
  const uint  numPaths = NumThreads;
  const uint  surfelId = pass==0 ? gl_WorkGroupID.x : (header.count-gl_WorkGroupID.z-1);

  const Surfel p   = surfels[surfelId];
  if(!isSurfelAlive(p)) {
    surfels[surfelId].irradiance = vec3(1,1,0) / scene.exposure;
    return;
    }

  const mat3   tbn = toTangent(decodeNormal(p.norm));

  Random rngState = Random(pcgHash(gl_LocalInvocationIndex));

  const uint i   = gl_LocalInvocationIndex;
  const vec3 ray = tbn * sampleHemisphereCos(i,numPaths,0);

  const GBuf hit = loadGBuf(p.payload);
  const vec3 pt  = evalLight(p.pos, ray, hit);

  float hitInv = 1.0/clamp(hit.rayT*0.4, 10.0, p.radius);
  reduction[i] = vec4(pt.rgb, hitInv);
  barrier();

  reduceIrr();

  if(gl_LocalInvocationIndex==0) {
    const vec4   pos4 = scene.viewProject * vec4(p.pos, 1.0);
    const float  rMin = pixelToWorld(MinCoverage, pos4.z/pos4.w);
    const float  rMax = min(pixelToWorld(DefaultCoverage, pos4.z/pos4.w), 65000);

    const float hitMean = float(numPaths)/max(reduction[0].w, eps); //harmonic mean
    surfels[surfelId].radius     = rMax;
    surfels[surfelId].radiusMean = min(max(hitMean, rMin), rMax * rEffScale);

    surfels[surfelId].irradiance = (reduction[0].rgb/float(numPaths));
    }
  }