#version 450

#include "lighting/surfels/surf_common.glsl"
#include "scene.glsl"
#include "common.glsl"

layout(local_size_x = 16, local_size_y = 16) in;

layout(std140, push_constant) uniform Push {
  vec3 originLwc;
  };
layout(binding = 0, std140) uniform UboScene {
  SceneDesc scene;
  };

layout(binding = 1) uniform sampler2D  gbufDiffuse;
layout(binding = 2) uniform usampler2D gbufNormal;
layout(binding = 3) uniform sampler2D  depth;
layout(binding = 4, std430) buffer SB0 { uvec4 count; Surfel surfels[]; };
layout(binding = 5, rgba32f) uniform image2D posTree;
layout(binding = 6, rgba16)  uniform image2D normTree;
layout(binding = 7, r32f)    uniform image2D pdfTree;
//
layout(binding = 11, rgba8) uniform image2D dbgImage;


vec3 worldPos(float z, ivec2 fragCoord, ivec2 screenSize) {
  const mat4 inv = scene.viewProjectLwcInv;
  const vec2 uv  = vec2(fragCoord+0.5)*scene.screenResInv;
  const vec4 pos = inv*vec4(uv * 2.0 - 1.0, z, 1);
  return pos.xyz/pos.w + originLwc;
  }

void main() {
  const ivec2 fragCoord  = ivec2(gl_GlobalInvocationID.xy);
  const ivec2 screenSize = ivec2(textureSize(depth,0));
  const bool  valid      = all(lessThan(fragCoord, screenSize));

  if(!valid)
    return;

  const float z    = texelFetch(depth,fragCoord,0).x;
  const bool  sky  = (z >= SKY_DEPTH);
  if(!sky)
    atomicAdd(count.y, 1);

  const vec3  norm = sky ? vec3(0) : normalFetch(gbufNormal,fragCoord);
  const vec3  wpos = sky ? vec3(0) : worldPos(z, fragCoord, screenSize);

  imageStore(posTree,  fragCoord, vec4(wpos,sky ? 0 : 1));
  imageStore(normTree, fragCoord, vec4(norm*0.5+0.5,0));
  imageStore(pdfTree,  fragCoord, vec4(sky ? 0 : 0.005));
  }
