#version 460

#include "lighting/surfels/surf_common.glsl"

layout(local_size_x = 128) in;

const uint NumThreads = gl_WorkGroupSize.x*gl_WorkGroupSize.y*gl_WorkGroupSize.z;

layout(std140, push_constant) uniform Push {
  vec3 originLwc;
  uint tileSize;
  };

layout(binding = 5, std430)            buffer SB0 { uvec4 count; Candidate candidate[]; } alloc;
layout(binding = 6, std430) readonly   buffer SB2 { uint  surfelList[]; };
layout(binding = 7, r32ui) uniform uimage2D surfCnts;
layout(binding = 8, r32ui) uniform uimage2D surfBins;

shared float reduction[NumThreads];

void reduceWeights(float w) {
  uint laneID = gl_LocalInvocationIndex;

  reduction[laneID] = w;
  barrier();

  for(uint stride = NumThreads/2; stride > 0; stride >>= 1) {
    if(laneID < stride) {
      reduction[laneID] += reduction[laneID + stride];
      }
    barrier();
    }
  }

float wangHashNoise(uvec2 uv, uint s) {
  uint seed = (uv.x*1664525u + uv.y) + s;
  uint hash = wangHash(seed) & 0xFFFF;
  return float(hash) / float(0xFFFF);
  }

void main() {
  const uint      surfelId = gl_WorkGroupID.x;
  const Candidate p        = alloc.candidate[surfelId];
  const vec3      wpos     = p.pos;
  const vec3      norm     = p.norm;

  const ivec2 tileId = p.fragCoord/int(tileSize);
  const uint  cnt    = imageLoad(surfCnts, tileId).x;
  const uint  ptr    = imageLoad(surfBins, tileId).x;

  float wSum = 0;
  for(uint i=gl_LocalInvocationIndex; i<cnt; i+=NumThreads) {
    const uint   sId = surfelList[ptr+i];
    if(sId==surfelId)
      continue;

    const Candidate s = alloc.candidate[sId];
    //const float w = calculteWeight(s.pos, s.norm, /*s.radiusMean*/ s.radius, s.radius, wpos, norm);
    //wSum += clamp(w,0,1);
    vec3  ldir   = wpos - s.pos;
    float dist   = length(ldir);
    float dotN   = dot(norm, s.norm);

    float rMax  = s.radius*0.5;
    float rEff  = min(rMax, rMax*0.5);
    float q     = max(min(dist,rMax)-rEff, 0)/(rMax-rEff);
    float wPos  = pow(1-q, 4.0)*(4.0*q + 1.0);
    float wNorm = pow(max(dotN, 0.0), 2.0);
    float wOccl = 1.0 - max(dot((ldir/dist), s.norm), 0.0);
    //float wPos  = 1;

    wSum += wPos * wNorm * wOccl;
    //wSum += pow(max(dot(s.norm,norm), 0.0), 2.0);
    }
  reduceWeights(wSum);

  if(gl_LocalInvocationIndex==0) {
    float w = reduction[0];
    alloc.candidate[surfelId].weight = exp(-w/64.0) + 0.25;
    // alloc.candidate[surfelId].weight = w;
    // alloc.candidate[surfelId].weight = 1.0/max(w, 1.0);
    }
  }