#version 450

#include "lighting/surfels/surf_common.glsl"
#include "scene.glsl"
#include "common.glsl"

layout(local_size_x = 8, local_size_y = 8) in;

const uint BVH_NullNode = 0x00000000;
const uint BVH_BoxNode  = 0x10000000;
const uint BVH_DataNode = 0x20000000;

struct BVHNode {
  ivec4 bbox;
  uint  ptrNext;
  uint  ptrMiss;
  ivec2 padd0;
  };

layout(std140, push_constant) uniform Push {
  vec3 originLwc;
  uint maxSurfels;
  };
layout(binding = 0, std140) uniform UboScene {
  SceneDesc scene;
  };

layout(binding = 1) uniform sampler2D  gbufDiffuse;
layout(binding = 2) uniform usampler2D gbufNormal;
layout(binding = 3) uniform sampler2D  depth;
layout(binding = 4, std430) readonly buffer SB0 { uvec4 count; Surfel surfels[]; };
layout(binding = 5, std430) readonly buffer SB1 { BVHNode bvh[]; };
//
layout(binding = 11, rgba8) uniform image2D dbgImage;

vec4 color = vec4(0);

vec3 worldPos(float z, ivec2 fragCoord, ivec2 screenSize) {
  const mat4 inv = scene.viewProjectLwcInv;
  const vec2 uv  = vec2(fragCoord+0.5)*scene.screenResInv;
  const vec4 pos = inv*vec4(uv * 2.0 - 1.0, z, 1);
  return (pos.xyz)/pos.w + originLwc;
  }

float calculteWeight(const Surfel s, const vec3 wpos, const vec3 norm) {
  return calculteWeight(s.pos.xyz, decodeNormal(s.norm), s.radiusMean, s.radius, wpos, norm);
  }

void shade(const Surfel s, const vec3 wpos, const vec3 norm, const vec3 clr) {
  float w = calculteWeight(s, wpos, norm);
  if(w<=0)
    return;
  color += vec4(clr*w, w);
  }

bool intersect(ivec2 fragCoord, ivec4 bbox) {
  return bbox.x <= fragCoord.x && fragCoord.x<bbox.z &&
         bbox.y <= fragCoord.y && fragCoord.y<bbox.w;
  }

int traverse(ivec2 fragCoord, const vec3 wpos, const vec3 norm) {
  int count = 0;

  uint ptr = (0 | BVH_BoxNode);
  while(ptr!=0xFFFFFFFF) {
    const uint    type = (ptr & 0xF0000000);
    const BVHNode b    = bvh[ptr & 0x0FFFFFFF];

    if(type==BVH_DataNode) {
      ptr = b.ptrMiss;
      for(uint i=b.padd0.x; i<b.padd0.y; ++i) {
        shade(surfels[i], wpos, norm, debugColors[i%debugColors.length()]);
        }
      count += (b.padd0.y-b.padd0.x);
      continue;
      }
    if(!intersect(fragCoord, b.bbox)) {
      ptr = b.ptrMiss;
      continue;
      }
    ptr = b.ptrNext;
    }

  return count;
  }

void main() {
  const ivec2 fragCoord  = ivec2(gl_GlobalInvocationID.xy);
  const ivec2 screenSize = ivec2(textureSize(depth,0));
  const bool  valid = all(lessThan(fragCoord, screenSize));
  if(!valid)
    return;

  const float z     = texelFetch(depth,fragCoord,0).x;
  const bool  sky   = (z >= SKY_DEPTH);
  if(sky)
    return;

  const vec3  norm = normalFetch(gbufNormal, fragCoord);
  const vec3  wpos = worldPos(z, fragCoord, screenSize);

  const uint v = traverse(fragCoord, wpos, norm);

  if(color.w>0)
    color.rgb /= color.w;

  //imageStore(dbgImage, fragCoord, vec4(v/255.0));
  imageStore(dbgImage, fragCoord, vec4(color.rgb, v/255.0));
  }