#version 460

#define LIGHTING 1
#define RAY_QUERY
#define RAY_QUERY_AT

#include "lighting/rt/rt_common.glsl"
#include "lighting/pt/pathtrace_common.glsl"
#include "lighting/surfels/surf_common.glsl"
#include "lighting/tonemapping.glsl"

#include "scene.glsl"
#include "common.glsl"
#include "random.glsl"

layout(local_size_x = 64) in;

layout(binding = 0, std140) uniform UboScene {
  SceneDesc scene;
  };
layout(binding = 1, std430) buffer SB0 { uvec4 count; Surfel surfels[]; };
layout(binding = 2) uniform sampler2D skyLUT;

mat3 toTangent(vec3 norm) {
  mat3 tangent;
  // Compute a tangent frame and rotate the half vector to world space
  vec3 up   = abs(norm.z) < 0.999f ? vec3(0.0f, 0.0f, 1.0f) : vec3(1.0f, 0.0f, 0.0f);
  tangent[0] = normalize(cross(up, norm));
  tangent[1] = cross(norm, tangent[0]);
  tangent[2] = norm;
  return tangent;
  }

float sampleDirectLight(vec3 norm, vec3 rayOrigin, vec3 rayDirection, bool shadowed, float softAngle, inout random rngState) {
#if defined(SOFT_SHADOW)
  vec3  shRay  = randomizeRay(rayDirection, 0.5*M_PI/180.0, rngState);
#else
  vec3  shRay  = rayDirection;
#endif

  float lamb   = max(dot(norm, rayDirection), 0);
  if(!shadowed || lamb==0)
    return lamb;

  float shadow = rayQueryProceedShadow(rayOrigin, shRay, rngState);
  // float shadow = shadowFactor(rayOrigin);
  return (lamb * shadow);
  }

vec4 pathtrace(vec3 rayOrigin, vec3 rayDirection, inout random rngState) {
  const int numBounces = 5;

  vec3  thruput    = vec3(1);
  vec3  color      = vec3(0);
  bool  underWater = (scene.underWater!=0);
  float depth      = 0;

  for(int bounce=0;; ++bounce) {
    if(dot(thruput*scene.GSunIntensity*scene.exposure, vec3(0.2126, 0.7152, 0.0722)) < 0.01)
      break;

    if(bounce>=numBounces) {
      // return 0.5*vec4(1,0,1,depth)*scene.GSunIntensity;
      // rescale to 100% thruput
      vec3 scale = 1.0-thruput;
      if(scale.r>0.01 && scale.g>0.01 && scale.b>0.01)
        return vec4(color/scale, depth);
      return vec4(color, depth);
      }

    HitResolve hit = rayQueryProceedPrimary(rayOrigin, rayDirection, (bounce==0 ? 0 : -1), rngState);
    if(bounce==0)
      depth = abs(hit.rayT);

    if(hit.rayT<0) {
      hit.rayT = abs(hit.rayT); // backfaces are fine for PT
      hit.norm = -hit.norm;
      }

    if(hit.rayT==TMax) {
      vec3 sky = textureSkyLUT(skyLUT, vec3(0,RPlanet+max(rayOrigin.y*0.01,0),0), rayDirection, scene.sunDir) * scene.GSunIntensity;
      color += thruput*sky;
      color += thruput*(vec3(0.3, 0.26, 1)*0.15); //HACK for the night sky
      break;
      }

    /*
    if(underWater) {
      const float depth         = hit.rayT / 5000.0; // 50 meters
      const vec3  transmittance = exp(-depth * vec3(4,2,1) * 1.25);
      thruput *= transmittance;
      }

    if(hit.water) {
      const float ior  = (underWater ? IorAir : IorWater);
      const vec3  refl = reflect(rayDirection, hit.norm);
      const float f    = fresnel(refl,hit.norm,ior);
      const bool  path = (f>randf(rngState));

      rayOrigin    = (rayOrigin + rayDirection * hit.rayT);
      rayDirection = path ? refl : refract(rayDirection, hit.norm, ior);
      underWater   = path ? underWater : !underWater;
      thruput    *= WaterAlbedo;
      continue;
      }
    */

    rayOrigin    = (rayOrigin + rayDirection * hit.rayT);
    rayDirection = randCosWeightedHemisphereDirection(hit.norm, rngState);
    thruput    *= textureAlbedo(hit.diff.rgb);
    //thruput    *= vec3(0.85); //snow
    //thruput    *= vec3(0.04); // asphalt
    //if(bounce>0)
    //  thruput *= groundAlbedo;
    //if(bounce>0)
    //  thruput    *= textureAlbedo(hit.diff.rgb);

    vec3  direct = vec3(0);
    direct += sampleDirectLight(hit.norm, rayOrigin, scene.sunDir, true, 0.54*M_PI/180.0, rngState) * scene.sunColor;
    color  += thruput*direct*Fd_Lambert;
    }

  return vec4(color, depth);
  }

void main() {
  const uint numPaths = 16;
  const uint surfelId = gl_GlobalInvocationID.x;
  if(surfelId>=count.x)
    return;

  random rngState = random(0);

  const Surfel p   = surfels[surfelId];
  const mat3   tbn = toTangent(decodeNormal(p.norm));

  vec3  irradiance = vec3(0);
  float hHit       = 0; // harmonic mean
  for(int i=0; i<numPaths; ++i) {
    // const vec3 ray = randCosWeightedHemisphereDirection(tbn, rngState);
    const vec3 ray = tbn * sampleHemisphereCos(i,numPaths,0).xzy;
    const vec4 pt  = pathtrace(p.pos, ray, rngState);

    irradiance.rgb += pt.rgb;
    hHit += 1.0/max(pt.a, 0.01);
    }

  surfels[surfelId].irradiance = (irradiance/float(numPaths));
  }