#version 450

#include "lighting/surfels/surf_common.glsl"
#include "scene.glsl"
#include "common.glsl"

layout(local_size_x = 256) in;

const uint NumThreads = gl_WorkGroupSize.x*gl_WorkGroupSize.y*gl_WorkGroupSize.z;

const uint BVH_NullNode = 0x00000000;
const uint BVH_BoxNode  = 0x10000000;
const uint BVH_DataNode = 0x20000000;

struct BVHNode {
  ivec4 bbox;
  uint  ptrNext;
  uint  ptrMiss;
  ivec2 padd0;
  };

struct Task {
  ivec4 bbox;
  uint  begin;
  uint  end;
  uint  bvhPtr;
  uint  ptrMiss;
  };

layout(std140, push_constant) uniform Push {
  vec3 originLwc;
  uint maxSurfels;
  };
layout(binding = 0, std140) uniform UboScene {
  SceneDesc scene;
  };

layout(binding = 1) uniform sampler2D  gbufDiffuse;
layout(binding = 2) uniform usampler2D gbufNormal;
layout(binding = 3) uniform sampler2D  depth;
layout(binding = 4, std430) buffer SB0 { uvec4 count; Surfel surfels[]; };
layout(binding = 5, std430) buffer SB1 { BVHNode bvh[]; };

shared uint  splitLeft;
shared uint  iteratorL, iteratorR;
shared ivec4 bboxA;
shared ivec4 bboxB;

shared Task  stack[32];
shared uint  stackPtr;

shared uint  bvhSize;

uint toBitHint(uint num) {
  return num>1 ? BVH_BoxNode : BVH_DataNode;
  }

void pushTask(ivec4 bbox, uint bvhPtr, uint ptrMiss, uint begin, uint end) {
  Task t;
  t.bbox    = bbox;
  t.begin   = begin;
  t.end     = end;
  t.bvhPtr  = bvhPtr;
  t.ptrMiss = ptrMiss;

  stack[stackPtr] = t;
  ++stackPtr;
  }

uint findSplit(uint bvhPtr, uint ptrMiss, uint begin, uint end, ivec2 bboxMin, ivec2 bboxMax) {
  const uint laneID = gl_LocalInvocationIndex;

  splitLeft  = begin;
  iteratorL  = begin;
  iteratorR  = end-1;
  bboxA      = ivec4(bboxMax, 0, 0);
  bboxB      = ivec4(bboxMax, 0, 0);
  barrier();

  int splitX = (bboxMin.x + bboxMax.x)/2;
  int splitY = (bboxMin.y + bboxMax.y)/2;

  if(bboxMax.x-bboxMin.x < bboxMax.y-bboxMin.y)
    splitX = 0x7FFFFFFF; else
    splitY = 0x7FFFFFFF;

  for(uint i=begin+laneID; i<end; i+=NumThreads) {
    Surfel s  = surfels[i];
    ivec2  at = s.fragCoord;
    if(at.x<splitX && at.y<splitY) {
      atomicAdd(splitLeft, 1);

      atomicMin(bboxA.x, at.x-s.radiusPix);
      atomicMin(bboxA.y, at.y-s.radiusPix);
      atomicMax(bboxA.z, at.x+s.radiusPix);
      atomicMax(bboxA.w, at.y+s.radiusPix);
      } else {
      atomicMin(bboxB.x, at.x-s.radiusPix);
      atomicMin(bboxB.y, at.y-s.radiusPix);
      atomicMax(bboxB.z, at.x+s.radiusPix);
      atomicMax(bboxB.w, at.y+s.radiusPix);
      }
    }
  barrier();

  while(true) {
    const uint i = atomicAdd(iteratorL,1);
    if(i>=splitLeft)
      break;
    Surfel si   = surfels[i];
    bool   left = (si.fragCoord.x<splitX && si.fragCoord.y<splitY);
    if(left)
      continue;

    // 'si' has to be swapped to the right
    while(true) {
      const uint r = atomicAdd(iteratorR,-1);
      Surfel sr   = surfels[r];
      bool   left = (sr.fragCoord.x<splitX && sr.fragCoord.y<splitY);
      if(left) {
        surfels[i] = sr;
        surfels[r] = si;
        break;
        }
      }
    }

  if(laneID==0) {
    const uint alloc = atomicAdd(bvhSize, 2);
    const uint ptrA  = (alloc+0) | toBitHint(splitLeft-begin);
    const uint ptrB  = (alloc+1) | toBitHint(end-splitLeft);

    BVHNode node;
    node.bbox    = ivec4(bboxMin, bboxMax);
    node.ptrNext = ptrA;
    node.ptrMiss = ptrMiss;
    node.padd0   = ivec2(0);
    bvh[bvhPtr] = node;

    pushTask(bboxA, ptrA, ptrB,    begin,     splitLeft);
    pushTask(bboxB, ptrB, ptrMiss, splitLeft, end);
    }

  memoryBarrierBuffer();
  return 0;
  }

bool nextTask() {
  const uint laneID = gl_LocalInvocationIndex;
  if(stackPtr==0)
    return true;
  Task t = stack[stackPtr-1];
  barrier();

  if(laneID==0) {
    --stackPtr;
    }
  barrier();

  const uint ptr = t.bvhPtr & 0x0FFFFFFF;

  if(stackPtr+2 < stack.length() && t.end - t.begin > 1) {
    findSplit(ptr, t.ptrMiss, t.begin, t.end, t.bbox.xy, t.bbox.zw);
    } else {
    //TODO: real leaf node
    if(laneID==0) {
      BVHNode node;
      node.bbox    = ivec4(0);
      node.ptrNext = t.ptrMiss;
      node.ptrMiss = t.ptrMiss;
      node.padd0   = ivec2(t.begin, t.end);
      bvh[ptr] = node;
      }
    }

  return false;
  }

void main() {
  stackPtr = 0;
  bvhSize  = 1;
  barrier();

  findSplit(0, 0xFFFFFFFF, 0, count.x, ivec2(0), textureSize(depth, 0));
  barrier();

  while(true) {
    const bool done = nextTask();
    barrier();

    if(done)
      break;
    }
  }