#version 460

#include "lighting/surfels/surf_common.glsl"

layout(local_size_x = 128) in;

const uint NumThreads = gl_WorkGroupSize.x*gl_WorkGroupSize.y*gl_WorkGroupSize.z;

layout(std140, push_constant) uniform Push {
  vec3 originLwc;
  uint tileSize;
  };

layout(binding = 5, std430)            buffer SB0 { uvec4 count; Candidate candidate[]; } alloc;
layout(binding = 6, std430) readonly   buffer SB2 { uint  surfelList[]; };
layout(binding = 7, r32ui) uniform uimage2D surfCnts;
layout(binding = 8, r32ui) uniform uimage2D surfBins;

shared float reduction[NumThreads];

void reduceWeights(float w) {
  uint laneID = gl_LocalInvocationIndex;

  reduction[laneID] = w;
  barrier();

  for(uint stride = NumThreads/2; stride > 0; stride >>= 1) {
    if(laneID < stride) {
      reduction[laneID] += reduction[laneID + stride];
      }
    barrier();
    }
  }

void main() {
  const uint      surfelId = gl_WorkGroupID.x;
  const Candidate p        = alloc.candidate[surfelId];
  const vec3      wpos     = p.pos;
  const vec3      norm     = p.norm;

  const ivec2 tileId = p.fragCoord/int(tileSize);
  const uint  cnt    = imageLoad(surfCnts, tileId).x;
  const uint  ptr    = imageLoad(surfBins, tileId).x;

  float wSum = 0;
  for(uint i=gl_LocalInvocationIndex; i<cnt; i+=NumThreads) {
    const uint   sId = surfelList[ptr+i];
    if(sId==surfelId)
      continue;

    const Candidate s = alloc.candidate[sId];
    wSum += calculteWeight(s.pos, s.norm, /*s.radiusMean*/ s.radius, s.radius, wpos, norm);
    }
  reduceWeights(wSum);

  if(gl_LocalInvocationIndex==0) {
    alloc.candidate[surfelId].weight = exp(-reduction[0]/64.0);
    }
  }