#version 450

#include "lighting/surfels/surf_common.glsl"
#include "scene.glsl"
#include "common.glsl"

const float fov      = 67.5f*M_PI/180.0;
const float cellSize = 25;

layout(local_size_x = 64) in;

layout(std140, push_constant) uniform Push {
  vec3 originLwc;
  };
layout(binding = 0, std140) uniform UboScene {
  SceneDesc scene;
  };

layout(binding = 1) uniform sampler2D  gbufDiffuse;
layout(binding = 2) uniform usampler2D gbufNormal;
layout(binding = 3) uniform sampler2D  depth;
layout(binding = 4, std430) buffer SB0 { uvec4 count; Surfel surfels[]; };
layout(binding = 5, std430) buffer SB1 { uint hashGrid[]; };

vec3 worldPos(float z, ivec2 fragCoord, ivec2 screenSize) {
  const mat4 inv = scene.viewProjectLwcInv;
  const vec2 uv  = vec2(fragCoord+0.5)*scene.screenResInv;
  const vec4 pos = inv*vec4(uv * 2.0 - 1.0, z, 1);
  return pos.xyz/pos.w + originLwc;
  }

ivec2 unpackSurfId(uint pkg, ivec2 screenSize) {
  pkg &= 0x0FFFFFF;
  return ivec2(pkg%screenSize.x, pkg/screenSize.x);
  }

void main() {
  const uint hKey = gl_GlobalInvocationID.x;
  if(hKey >= hashGrid.length())
    return;

  const uint sId = hashGrid[hKey];
  if(sId==0xFFFFFFFF)
    return;

  const ivec2 screenSize = ivec2(textureSize(depth,0));
  const ivec2 fragCoord  = unpackSurfId(sId, screenSize);

  const uint id = atomicAdd(count.x, 1);
  if(id>=surfels.length())
    return;

  const float z   = texelFetch(depth, fragCoord, 0).x;
  const vec3  pos = worldPos(z, fragCoord, screenSize);

  Surfel sx;
  sx.pos  = pos;
  sx.norm = texelFetch(gbufNormal, fragCoord, 0).r;
  surfels[id] = sx;
  }
