#version 460

#define LIGHTING 1
#define RAY_QUERY
#define RAY_QUERY_AT

#include "lighting/rt/rt_common.glsl"
#include "lighting/pt/pathtrace_common.glsl"
#include "lighting/surfels/surf_common.glsl"
#include "lighting/tonemapping.glsl"

#include "scene.glsl"
#include "common.glsl"
#include "random.glsl"

layout(local_size_x = 8, local_size_y = 8) in;

const uint NumThreads = gl_WorkGroupSize.x*gl_WorkGroupSize.y*gl_WorkGroupSize.z;

layout(std140, push_constant) uniform Push {
  uint pass;
  };
layout(binding = 0, std140) uniform UboScene {
  SceneDesc scene;
  };
layout(binding = 1, std430) buffer SB0 { SurfHeader header; Surfel surfels[]; };
layout(binding = 2)         uniform sampler2D skyLUT;
layout(binding = 3, rgba8)  uniform image2D   gbufDiff;
layout(binding = 4, rgba8)  uniform image2D   gbufNorm;

mat3 toTangent(vec3 norm) {
  mat3 tangent;
  // Compute a tangent frame and rotate the half vector to world space
  vec3 up   = abs(norm.z) < 0.999f ? vec3(0.0f, 0.0f, 1.0f) : vec3(1.0f, 0.0f, 0.0f);
  tangent[0] = normalize(cross(up, norm));
  tangent[1] = cross(norm, tangent[0]);
  tangent[2] = norm;
  return tangent;
  }

float sampleDirectLight(vec3 norm, vec3 rayOrigin, vec3 rayDirection) {
  vec3  shRay  = rayDirection;

  float lamb   = max(dot(norm, rayDirection), 0);
  if(lamb==0)
    return lamb;

  Random rngState = Random(0);
  float shadow = rayQueryProceedShadow(rayOrigin, shRay, rngState);
  return (lamb * shadow);
  }

HitResolve raycast(vec3 rayOrigin, vec3 rayDirection, inout Random rngState) {
  HitResolve hit = rayQueryProceedPrimary(rayOrigin, rayDirection, -1, rngState);
  if(hit.rayT<0) {
    hit.rayT = -hit.rayT; // backfaces are fine
    hit.norm = -hit.norm;
    }
  if(hit.rayT==TMax)
    hit.diff = vec4(0,0,1,1);
  return hit;
  }

vec3 evalLight(vec3 rayOrigin, vec3 rayDirection, HitResolve hit) {
  vec3  thruput = min(textureAlbedo(hit.diff.rgb), 0.95);
  float depth   = hit.rayT;
  vec3  color   = vec3(0);

  if(hit.rayT==TMax) {
    vec3 sky = textureSkyLUT(skyLUT, vec3(0,RPlanet+max(rayOrigin.y*0.01,0),0), rayDirection, scene.sunDir) * scene.GSunIntensity;
    color += sky;
    color += (vec3(0.3, 0.26, 1)*0.15); //HACK for the night sky
    return color;
    }

  rayOrigin    = (rayOrigin + rayDirection * hit.rayT);

  vec3  direct = vec3(0);
  direct += sampleDirectLight(hit.norm, rayOrigin, scene.sunDir) * scene.sunColor;
  color  += thruput*direct*Fd_Lambert;

  return color;
  }

shared vec4 reduction[NumThreads];
shared uint hitCnt;

void reduceIrr() {
  uint laneID = gl_LocalInvocationIndex;

  for(uint stride = NumThreads/2; stride > 0; stride >>= 1) {
    if(laneID < stride) {
      reduction[laneID].rgb += reduction[laneID + stride].rgb;
      reduction[laneID].a   += reduction[laneID + stride].a;
      }
    barrier();
    }
  }

void storeGBuf(uint ptr, const HitResolve hit) {
  if(ptr==0)
    return; //error
  uint x = ((ptr >>  0) & 0xFFF);
  uint y = ((ptr >> 12) & 0xFFF);

  ivec2 at = ivec2(x,y)*8 + ivec2(gl_LocalInvocationID.xy);
  imageStore(gbufDiff, at, vec4(hit.diff.rgb, 1));
  imageStore(gbufNorm, at, vec4(hit.norm.xyz*0.5+0.5, 1));
  }

void main() {
  const float eps      = 0.0001;
  const uint  numPaths = NumThreads;
  const uint  surfelId = pass==0 ? gl_WorkGroupID.x : (header.count-gl_WorkGroupID.z-1);
  // if(surfelId>=header.count)
  //   return;

  const Surfel p   = surfels[surfelId];
  const mat3   tbn = toTangent(decodeNormal(p.norm));

  Random rngState = Random(pcgHash(gl_LocalInvocationIndex));

  const uint i   = gl_LocalInvocationIndex;
  const vec3 ray = tbn * sampleHemisphereCos(i,numPaths,0);

  const HitResolve hit = raycast(p.pos, ray, rngState);
  const vec3       pt  = evalLight(p.pos, ray, hit);

  hitCnt = 0;
  barrier();

  if(hit.rayT!=TMax)
    atomicAdd(hitCnt, 1);

  storeGBuf(p.payload, hit);

  reduction[i] = vec4(pt.rgb, 1.0/clamp(hit.rayT*0.4, 10.0, 1*p.radius));
  barrier();

  reduceIrr();

  if(gl_LocalInvocationIndex==0) {
    const float hitMean = float(numPaths)/max(reduction[0].a, eps); //harmonic mean
    surfels[surfelId].radiusMean = hitMean;
    surfels[surfelId].irradiance = (reduction[0].rgb/float(numPaths));
    }
  }