#version 460

#extension GL_EXT_shader_explicit_arithmetic_types_int32 : enable

layout(local_size_x = 16, local_size_y = 16) in;

#include "lighting/surfels/surf_common.glsl"
#include "scene.glsl"

const uint NumThreads = gl_WorkGroupSize.x*gl_WorkGroupSize.y*gl_WorkGroupSize.z;

const float NormalBias  = 0.0030;

layout(std140, push_constant) uniform Push {
  vec3 originLwc;
  };
layout(binding = 0, std140) uniform UboScene {
  SceneDesc scene;
  };
layout(binding = 1) uniform sampler2D  gbufDiffuse;
layout(binding = 2) uniform usampler2D gbufNormal;
layout(binding = 3) uniform sampler2D  depth;
layout(binding = 4, std430) readonly   buffer SB1 { uvec4 count; Surfel    surfels[];   } surf;
layout(binding = 5, std430)            buffer SB0 { uvec4 count; Candidate candidate[]; } alloc;
//
layout(binding = 11, rgba8) uniform image2D dbgImage;

shared uint32_t fragVote;

uint32_t packVote(uint weight, uint32_t key) {
  uint32_t  w = (weight << 16) & 0xFFFF0000;
  return uint32_t(w) | uint32_t(key & 0x0000FFFF);
  }

uint32_t unpackVoteKey(uint vote) {
  return uint32_t(vote & 0x0000FFFF);
  }

uint wangHashNoise(uvec2 uv, uint s) {
  uint seed = (uv.x*1664525u + uv.y) + s;
  uint hash = wangHash(seed) & 0xFFFF;
  return hash;
  //float value = float(hash) / float(0xFFFF);
  //return value;
  }

uint hash3(uvec3 p) {
  p = p * 1664525u + 1013904223u;

  p.x += p.y * p.z;
  p.y += p.z * p.x;
  p.z += p.x * p.y;

  p ^= p >> 16u;

  p.x += p.y * p.z;
  p.y += p.z * p.x;
  p.z += p.x * p.y;

  return p.x ^ p.y ^ p.z;
  }

vec3 worldPos(float z, vec3 normal, ivec2 fragCoord, ivec2 screenSize) {
  const mat4 inv = scene.viewProjectLwcInv;
  const vec2 uv  = vec2(fragCoord+0.5)*scene.screenResInv;
  const vec4 pos = inv*vec4(uv * 2.0 - 1.0, z, 1);
  return (pos.xyz + normal*NormalBias)/pos.w + originLwc;
  }

float pixelToWorld(float pixelRadius, float z) {
  z = linearDepth(z, scene.clipInfo);

  float clipRadiusX = (2.0 * pixelRadius) * scene.screenResInv.x;
  float clipRadiusY = (2.0 * pixelRadius) * scene.screenResInv.y;

  float worldRadiusX = (clipRadiusX * z) / scene.project[0][0];
  float worldRadiusY = (clipRadiusY * z) / scene.project[1][1];
  return min(worldRadiusX, worldRadiusY);
  }

void main() {
  const uint laneID = gl_LocalInvocationIndex;

  fragVote = packVote(0xFFFF, 0xFFFF);
  barrier();

  const ivec2 fragCoord  = ivec2(gl_GlobalInvocationID.xy);
  const ivec2 screenSize = ivec2(textureSize(depth,0));
  const bool  valid      = all(lessThan(fragCoord, screenSize));

  // const ivec2 tileId = ivec2(gl_WorkGroupID.xy*gl_WorkGroupSize.xy)/int(tileSize);
  // const uint  cnt    = imageLoad(surfCnts, tileId).x;
  // const uint  ptr    = imageLoad(surfBins, tileId).x;

  const float z    = valid ? texelFetch(depth,fragCoord,0).x : 1;
  const vec3  norm = normalFetch(gbufNormal, fragCoord);
  const vec3  wpos = worldPos(z, norm, fragCoord, screenSize);
  const bool  sky  = (z >= SKY_DEPTH);

  if(!sky) {
    const uint rand = wangHashNoise(fragCoord, 0);
    // const uint rand = hash3(uvec3(wpos/1.0));
    atomicMin(fragVote, packVote(rand, gl_LocalInvocationIndex));
    imageStore(dbgImage, fragCoord, vec4(float(rand)/float(0xFFFF)));
    }
  barrier();

  if(unpackVoteKey(fragVote)!=gl_LocalInvocationIndex)
    return;

  const uint surfelId = atomicAdd(alloc.count.x,1);

  Candidate sx;
  sx.pos        = wpos;
  sx.norm       = norm;
  sx.radius     = pixelToWorld(DefaultCoverage, z);
  sx.fragCoord  = fragCoord;

  //sx.radiusMean = sx.radius;
  //sx.radiusPix  = DefaultCoverage;
  //sx.irradiance = surfDebugColor(wpos, surfelId);

  alloc.candidate[surfelId] = sx;
  }