#version 450

#include "lighting/surfels/surf_common.glsl"
#include "scene.glsl"
#include "common.glsl"

layout(local_size_x = 256) in;

const uint NumThreads = gl_WorkGroupSize.x*gl_WorkGroupSize.y*gl_WorkGroupSize.z;

layout(binding = 4, std430) buffer SB0 { uvec4 count; Surfel surfels[]; };
layout(binding = 5, std430) buffer SB1 { uint usage[]; };

shared uint wPtr;

void main() {
  const uint laneID = gl_LocalInvocationIndex;

  wPtr = 0;
  barrier();

  Surfel sx;
  for(uint ix=0; ix<count.x; ix+=NumThreads) {
    const uint i   = ix+laneID;
    const uint bit = (1u << (i % 32));
    if(i<count.x && (usage[i/32] & bit)!=0) {
      sx = surfels[i];
      }
    barrier();

    if(i<count.x && (usage[i/32] & bit)!=0) {
      const uint w = atomicAdd(wPtr, 1);
      surfels[w] = sx;
      }
    }
  barrier();

  if(laneID==0) {
    count = uvec4(wPtr,1,1,0);
    }

  for(uint i=laneID; i<usage.length(); i+=NumThreads) {
    usage[i] = 0;
    }
  }
