#version 450

#include "lighting/lightstree/lights_common.glsl"
#include "lighting/lightstree/bvh_build_common.glsl"
#include "scene.glsl"
#include "common.glsl"

layout(local_size_x = 64) in;

const uint NumThreads = gl_WorkGroupSize.x*gl_WorkGroupSize.y*gl_WorkGroupSize.z;

layout(binding = 0, std430) readonly buffer LS {
  LightSource lights[];
  };

layout(binding = 1, std430) readonly buffer B1 {
  MortonHeader header; MortonPair morton[];
  };

layout(binding = 2, std430) buffer B2 {
  PTreeNode nodes[];
  };

layout(binding = 3, std430) buffer B3 {
  BVHAlux alux[];
  };

layout(binding = 4, std430) buffer B4 {
  uint parentbits[];
  };

void computeHeirarchy(const LightSource light, uint nodeId) {
  float weight = light.range * grayscale(light.color) + 1;
  vec3  center = light.pos;

  nodes[nodeId].centerL = center;
  nodes[nodeId].weightL = weight;
  nodes[nodeId].centerR = light.color;
  nodes[nodeId].weightR = light.range;
  //TODO: ball-tree?

  while(nodeId>0) {
    const uint parent  = alux[nodeId].parent;
    const uint parentL = nodes[parent].ptrL & 0x0FFFFFFF;
    if(parentL==nodeId) {
      nodes[parent].centerL = center;
      nodes[parent].weightL = weight;
      } else {
      nodes[parent].centerR = center;
      nodes[parent].weightR = weight;
      }

    const uint bit = 1u << (parent%32);
    memoryBarrierBuffer();
    if((atomicXor(parentbits[parent/32], bit) & bit)==0) {
      break;
      }

    nodeId = parent;

    PTreeNode node = nodes[nodeId];
    weight = node.weightL + node.weightR;
    center = node.centerL*node.weightL + node.centerR*node.weightR;
    if(weight>0) {
      center /= weight;
      }
    }
  }

void emitTrivialBVH() {
  nodes[0].centerL = vec3(0);
  nodes[0].weightL = 0;
  nodes[0].ptrL    = BVH_NullNode;
  nodes[0].centerR = vec3(0);
  nodes[0].weightR = 0;
  nodes[0].ptrR    = BVH_NullNode;
  }

void emitTrivialBVH(const LightSource light) {
  float weight = light.range * grayscale(light.color) + 1;
  vec3  center = light.pos;

  nodes[1].centerL = center;
  nodes[1].weightL = weight;
  nodes[1].centerR = light.color;
  nodes[1].weightR = light.range;

  nodes[0].centerL = center;
  nodes[0].weightL = weight;
  nodes[0].ptrL    = 1 | BVH_LightNode;
  nodes[0].centerR = vec3(0);
  nodes[0].weightR = 0;
  nodes[0].ptrR    = BVH_NullNode;
  }


void main() {
  const uint i = gl_GlobalInvocationID.x;
  if(header.numActiveLights==0) {
    emitTrivialBVH();
    return;
    }

  if(i >= header.numActiveLights)
    return;

  if(header.numActiveLights==1) {
    emitTrivialBVH(lights[morton[0].id]);
    return;
    }

  const uint internalCount = header.numActiveLights - 1;
  computeHeirarchy(lights[morton[i].id], internalCount + i);
  }
