#version 450

#extension GL_GOOGLE_include_directive : enable

#define CULL
#include "materials/materials_common.glsl"

layout(local_size_x = 32) in;

void initIndirectCmd(inout IndirectCmd cmd) {
  }

void main() {
  const uint i = gl_GlobalInvocationID.x;
  if(i>=cmd.length())
    return;

  const uint isMeshShader = 0;
  cmd[i].vertexCount   = 64*3;
  cmd[i].instanceCount = 0;
  cmd[i].firstVertex   = isMeshShader;
  cmd[i].firstInstance = isMeshShader;
  }
