#pragma once

#include <cstdint>
//#include "mem32.h"

namespace Compatibility {

using ptr32_t = uint32_t;

struct zString {
  int32_t _VTBL;
  int32_t _ALLOCATER;
  ptr32_t ptr;
  int32_t len;
  int32_t RES;
  };

struct zCArray {
  ptr32_t ptr = 0;
  int32_t numAlloc   = 0;
  int32_t numInArray = 0;
  };

struct zCArraySort {
  ptr32_t ptr = 0;
  int32_t numAlloc   = 0;
  int32_t numInArray = 0;
  ptr32_t compare = 0;
  };

struct zCListSort {
  ptr32_t compareFunc = 0;
  ptr32_t data = 0;
  ptr32_t next = 0;
  };

struct zCParser {
  int32_t msgfunc;

  int32_t file_array;                             //0x0004 zCPar_File**
  int32_t file_numAlloc;                          //0x0008 int
  int32_t file_numInArray;                        //0x000C int

  int32_t symtab_preAllocatedSymbols;             //0x0010 zCPar_Symbol*
  int32_t symtab_nextPreAllocated;                //0x0014 int

  zCArray  symtab_table;                          // array of pointers
  zCArraySort sorted_symtab_table;

  int32_t lastsym;                                //0x0034 zCPar_Symbol*
  int32_t firstsym;                               //0x0038 zCPar_Symbol*

  int32_t stringtab_array_array;
  int32_t stringtab_array_numAlloc;
  int32_t stringtab_array_numInArray;

  //zCPar_Stack               stack;
  ptr32_t stack_stack;
  ptr32_t stack_stackptr;
  int32_t stack_stacklast;
  int32_t stack_stacksize;

  //zCPar_DataStack           datastack;
  int32_t datastack_stack[2048];
  int32_t datastack_sptr;

  //NOTE: incomplete
  };

struct zCPar_Symbol {
  zString name;
  ptr32_t next;

  int32_t content;
  int32_t offset;

  int32_t bitfield;
  int32_t filenr;
  int32_t line;
  int32_t line_anz;
  int32_t pos_beg;
  int32_t pos_anz;

  ptr32_t parent;
  };

struct oGame {
  int32_t _VTBL;
  ptr32_t _ZCSESSION_CSMAN  = 0;
  ptr32_t _ZCSESSION_WORLD  = 0;
  ptr32_t _ZCSESSION_CAMERA = 0;
  int32_t _ZCSESSION_AICAM;
  int32_t _ZCSESSION_CAMVOB;
  ptr32_t _ZCSESSION_VIEWPORT;
  int32_t CLIPRANGE;
  int32_t FOGRANGE;
  int32_t INSCRIPTSTARTUP;
  int32_t INLOADSAVEGAME;
  int32_t INLEVELCHANGE;
  ptr32_t ARRAY_VIEW[6];
  int32_t ARRAY_VIEW_VISIBLE[6];
  int32_t ARRAY_VIEW_ENABLED[6];
  int32_t SAVEGAMEMANAGER;
  int32_t GAME_TEXT;
  int32_t LOAD_SCREEN;
  int32_t SAVE_SCREEN;
  int32_t PAUSE_SCREEN;
  ptr32_t HPBAR;
  ptr32_t SWIMBAR;
  ptr32_t MANABAR;
  ptr32_t FOCUSBAR;
  int32_t SHOWPLAYERSTATUS;
  int32_t GAME_DRAWALL;
  int32_t GAME_FRAMEINFO;
  int32_t GAME_SHOWANIINFO;
  int32_t GAME_SHOWWAYNET;
  int32_t GAME_TESTMODE;
  int32_t GAME_EDITWAYNET;
  int32_t GAME_SHOWTIME;
  int32_t GAME_SHOWRANGES;
  int32_t DRAWWAYBOXES;
  int32_t SCRIPTSTARTUP;
  int32_t SHOWFREEPOINTS;
  int32_t SHOWROUTINENPC;
  int32_t LOADNEXTLEVEL;
  zString LOADNEXTLEVELNAME;
  zString LOADNEXTLEVELSTART;
  int32_t STARTPOS[3];
  int32_t GAMEINFO;
  int32_t PL_LIGHT;
  int32_t PL_LIGHTVAL;
  ptr32_t WLDTIMER;
  int32_t TIMESTEP;
  int32_t SINGLESTEP;
  int32_t GUILDS;
  int32_t INFOMAN;
  int32_t NEWSMAN;
  int32_t SVMMAN;
  int32_t TRADEMAN;
  int32_t PORTALMAN;
  int32_t SPAWNMAN;
  int32_t MUSIC_DELAY;
  int32_t WATCHNPC;
  int32_t M_BWORLDENTERED;
  int32_t M_FENTERWORLDTIMER;
  int32_t INITIAL_HOUR;
  int32_t INITIAL_MINUTE;
  int32_t DEBUGINSTANCES_ARRAY;
  int32_t DEBUGINSTANCES_NUMALLOC;
  int32_t DEBUGINSTANCES_NUMINARRAY;
  int32_t DEBUGCHANNELS;
  int32_t DEBUGALLINSTANCES;
  int32_t OLDROUTINEDAY;
  int32_t OBJROUTINELIST_COMPAREFUNC;
  int32_t OBJROUTINELIST_DATA;
  int32_t OBJROUTINELIST_NEXT;
  int32_t CURRENTOBJECTROUTINE;
  int32_t PROGRESSBAR;
  int32_t VISUALLIST_ARRAY;
  int32_t VISUALLIST_NUMALLOC;
  int32_t VISUALLIST_NUMINARRAY;
  };

struct oWorld {
  int32_t _VTBL;
  int32_t _ZCOBJECT_REFCTR;
  int32_t _ZCOBJECT_HASHINDEX;
  int32_t _ZCOBJECT_HASHNEXT;
  zString _ZCOBJECT_OBJECTNAME;
  int32_t GLOBALVOBTREE_PARENT;
  int32_t GLOBALVOBTREE_FIRSTCHILD;
  int32_t GLOBALVOBTREE_NEXT;
  int32_t GLOBALVOBTREE_PREV;
  int32_t GLOBALVOBTREE_DATA;
  int32_t FOUNDHIT;
  int32_t FOUNDVOB;
  int32_t FOUNDPOLY;
  int32_t FOUNDINTERSECTION[3];
  int32_t FOUNDPOLYNORMAL[3];
  int32_t FOUNDVERTEX;
  int32_t OWNERSESSION;
  int32_t CSPLAYER;
  zString M_STRLEVELNAME;
  int32_t COMPILED;
  int32_t COMPILEDEDITORMODE;
  int32_t TRACERAYIGNOREVOBFLAG;
  int32_t M_BISINVENTORYWORLD;
  int32_t WORLDRENDERMODE;
  ptr32_t WAYNET;
  int32_t MASTERFRAMECTR;
  int32_t VOBFARCLIPZ;
  int32_t VOBFARCLIPZSCALABILITY;
  int32_t TRACERAYVOBLIST_ARRAY;
  int32_t TRACERAYVOBLIST_NUMALLOC;
  int32_t TRACERAYVOBLIST_NUMINARRAY;
  int32_t TRACERAYTEMPIGNOREVOBLIST_ARRAY;
  int32_t TRACERAYTEMPIGNOREVOBLIST_NUMALLOC;
  int32_t TRACERAYTEMPIGNOREVOBLIST_NUMINARRAY;
  int32_t RENDERINGFIRSTTIME;
  int32_t SHOWWAYNET;
  int32_t SHOWTRACERAYLINES;
  int32_t PROGRESSBAR;
  int32_t UNARCHIVEFILELEN;
  int32_t UNARCHIVESTARTPOSVOBTREE;
  int32_t NUMVOBSINWORLD;
  int32_t PERFRAMECALLBACKLIST_ARRAY;
  int32_t PERFRAMECALLBACKLIST_NUMALLOC;
  int32_t PERFRAMECALLBACKLIST_NUMINARRAY;
  int32_t SKYCONTROLERINDOOR;
  ptr32_t SKYCONTROLEROUTDOOR;
  int32_t ACTIVESKYCONTROLER;
  int32_t ZONEGLOBALLIST_ARRAY;
  int32_t ZONEGLOBALLIST_NUMALLOC;
  int32_t ZONEGLOBALLIST_NUMINARRAY;
  int32_t ZONEACTIVELIST_ARRAY;
  int32_t ZONEACTIVELIST_NUMALLOC;
  int32_t ZONEACTIVELIST_NUMINARRAY;
  int32_t ZONEACTIVELIST_COMPARE;
  int32_t ZONELASTCLASSLIST_ARRAY;
  int32_t ZONELASTCLASSLIST_NUMALLOC;
  int32_t ZONELASTCLASSLIST_NUMINARRAY;
  int32_t ZONELASTCLASSLIST_COMPARE;
  int32_t ZONEBOXSORTER_VTBL;
  int32_t ZONEBOXSORTER_HANDLES_ARRAY;
  int32_t ZONEBOXSORTER_HANDLES_NUMALLOC;
  int32_t ZONEBOXSORTER_HANDLES_NUMINARRAY;
  int32_t ZONEBOXSORTER_NODELIST0_ARRAY;
  int32_t ZONEBOXSORTER_NODELIST0_NUMALLOC;
  int32_t ZONEBOXSORTER_NODELIST0_NUMINARRAY;
  int32_t ZONEBOXSORTER_NODELIST0_COMPARE;
  int32_t ZONEBOXSORTER_NODELIST1_ARRAY;
  int32_t ZONEBOXSORTER_NODELIST1_NUMALLOC;
  int32_t ZONEBOXSORTER_NODELIST1_NUMINARRAY;
  int32_t ZONEBOXSORTER_NODELIST1_COMPARE;
  int32_t ZONEBOXSORTER_NODELIST2_ARRAY;
  int32_t ZONEBOXSORTER_NODELIST2_NUMALLOC;
  int32_t ZONEBOXSORTER_NODELIST2_NUMINARRAY;
  int32_t ZONEBOXSORTER_NODELIST2_COMPARE;
  int32_t ZONEBOXSORTER_SORTED;
  int32_t ZONEACTIVEHANDLE_VTBL;
  int32_t ZONEACTIVEHANDLE_MYSORTER;
  int32_t ZONEACTIVEHANDLE_MINS[3];
  int32_t ZONEACTIVEHANDLE_MAXS[3];
  int32_t ZONEACTIVEHANDLE_INDEXBEGIN[3];
  int32_t ZONEACTIVEHANDLE_INDEXEND[3];
  int32_t ZONEACTIVEHANDLE_ACTIVELIST_ARRAY;
  int32_t ZONEACTIVEHANDLE_ACTIVELIST_NUMALLOC;
  int32_t ZONEACTIVEHANDLE_ACTIVELIST_NUMINARRAY;
  int32_t ADDZONESTOWORLD;
  int32_t SHOWZONESDEBUGINFO;
  int32_t CBSPTREE;
  int32_t BSPTREE_ACTNODEPTR;
  int32_t BSPTREE_ACTLEAFPTR;
  int32_t BSPTREE_BSPROOT;
  int32_t BSPTREE_MESH;
  int32_t BSPTREE_TREEPOLYLIST;
  int32_t BSPTREE_NODELIST;
  int32_t BSPTREE_LEAFLIST;
  int32_t BSPTREE_NUMNODES;
  int32_t BSPTREE_NUMLEAFS;
  int32_t BSPTREE_NUMPOLYS;
  int32_t BSPTREE_RENDERVOBLIST_ARRAY;
  int32_t BSPTREE_RENDERVOBLIST_NUMALLOC;
  int32_t BSPTREE_RENDERVOBLIST_NUMINARRAY;
  int32_t BSPTREE_RENDERLIGHTLIST_ARRAY;
  int32_t BSPTREE_RENDERLIGHTLIST_NUMALLOC;
  int32_t BSPTREE_RENDERLIGHTLIST_NUMINARRAY;
  int32_t BSPTREE_SECTORLIST_ARRAY;
  int32_t BSPTREE_SECTORLIST_NUMALLOC;
  int32_t BSPTREE_SECTORLIST_NUMINARRAY;
  int32_t BSPTREE_PORTALLIST_ARRAY;
  int32_t BSPTREE_PORTALLIST_NUMALLOC;
  int32_t BSPTREE_PORTALLIST_NUMINARRAY;
  int32_t BSPTREE_BSPTREEMODE;
  int32_t BSPTREE_WORLDRENDERMODE;
  int32_t BSPTREE_VOBFARCLIPZ;
  int32_t BSPTREE_VOBFARPLANE[4];
  int32_t BSPTREE_VOBFARPLANESIGNBITS;
  int32_t BSPTREE_DRAWVOBBBOX3D;
  int32_t BSPTREE_LEAFSRENDERED;
  int32_t BSPTREE_VOBSRENDERED;
  int32_t BSPTREE_M_BRENDEREDFIRSTTIME;
  int32_t BSPTREE_MASTERFRAMECTR;
  int32_t BSPTREE_ACTPOLYPTR;
  int32_t BSPTREE_COMPILED;
  int32_t ACTIVEVOBLIST_ARRAY;
  int32_t ACTIVEVOBLIST_NUMALLOC;
  int32_t ACTIVEVOBLIST_NUMINARRAY;
  int32_t WALKLIST_ARRAY;
  int32_t WALKLIST_NUMALLOC;
  int32_t WALKLIST_NUMINARRAY;
  int32_t VOBHASHTABLESTART[2048];
  int32_t VOBHASHTABLEMIDDLE[2048];
  int32_t VOBHASHTABLEEND[2048];
  zString WORLDFILENAME;
  zString WORLDNAME;
  int32_t VOBLIST;
  ptr32_t VOBLIST_NPCS;
  int32_t VOBLIST_ITEMS;
  };

struct GameMgr {
  };

struct zError {
  int32_t _VTBL;
  int32_t ONEXIT;
  zString FILTER_AUTHORS;
  int32_t FILTER_FLAG;
  int32_t FILTER_LEVEL;
  int32_t TARGET;
  int32_t ACK_TYPE;
  int32_t LOG_FILE;
  int32_t INDENT_DEPTH;
  int32_t SPYHANDLE;
  int32_t SPYMUTEX;
  };

struct zCTimer {
  int32_t FACTORMOTION;
  int32_t FRAMETIMEFLOAT;
  int32_t TOTALTIMEFLOAT;
  int32_t FRAMETIMEFLOATSECS;
  int32_t TOTALTIMEFLOATSECS;
  int32_t LASTTIMER;
  int32_t FRAMETIME;
  int32_t TOTALTIME;
  int32_t MINFRAMETIME;
  int32_t FORCEDMAXFRAMETIME;
  };

struct zCView {
  int32_t _VTBL;
  int32_t _ZCINPUTCALLBACK_VTBL;
  int32_t M_BFILLZ;
  int32_t NEXT;
  int32_t VIEWID;
  int32_t FLAGS;
  int32_t INTFLAGS;
  int32_t ONDESK;
  int32_t ALPHAFUNC;
  int32_t COLOR;
  int32_t ALPHA;
  int32_t CHILDS_COMPARE;
  int32_t CHILDS_COUNT;
  int32_t CHILDS_LAST;
  int32_t CHILDS_WURZEL;
  int32_t OWNER;
  int32_t BACKTEX;
  int32_t VPOSX;
  int32_t VPOSY;
  int32_t VSIZEX;
  int32_t VSIZEY;
  int32_t PPOSX;
  int32_t PPOSY;
  int32_t PSIZEX;
  int32_t PSIZEY;
  int32_t FONT;
  int32_t FONTCOLOR;
  int32_t PX1;
  int32_t PY1;
  int32_t PX2;
  int32_t PY2;
  int32_t WINX;
  int32_t WINY;
  int32_t TEXTLINES_DATA;
  int32_t TEXTLINES_NEXT;
  int32_t SCROLLMAXTIME;
  int32_t SCROLLTIMER;
  int32_t FXOPEN;
  int32_t FXCLOSE;
  int32_t TIMEDIALOG;
  int32_t TIMEOPEN;
  int32_t TIMECLOSE;
  int32_t SPEEDOPEN;
  int32_t SPEEDCLOSE;
  int32_t ISOPEN;
  int32_t ISCLOSED;
  int32_t CONTINUEOPEN;
  int32_t CONTINUECLOSE;
  int32_t REMOVEONCLOSE;
  int32_t RESIZEONOPEN;
  int32_t MAXTEXTLENGTH;
  zString TEXTMAXLENGTH;
  int32_t POSCURRENT_0[2];
  int32_t POSCURRENT_1[2];
  int32_t POSOPENCLOSE_0[2];
  int32_t POSOPENCLOSE_1[2];
  };

struct zCFontMan {
  };
}
