#version 450

#extension GL_GOOGLE_include_directive    : enable
#extension GL_ARB_separate_shader_objects : enable
#extension GL_EXT_samplerless_texture_functions : enable

#include "virtual_shadow/vsm_common.glsl"
#include "scene.glsl"

layout(local_size_x = 64) in;

layout(binding = 0, std430) buffer Omni { uint pageTblOmni[]; };

void main() {
  if(gl_GlobalInvocationID.x<pageTblOmni.length()) {
    pageTblOmni[gl_GlobalInvocationID.x] = 0;
    }
  }
